[package]
name = "loxrust"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
trace_exec = []

[dev-dependencies]
insta = { version = "1.43.2", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
